services:
  api:
    container_name: esecreditcard
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8083
    ports:
      - "8083:8083"
    volumes:
      - .:/app
    networks:
      - eseklugdorow
    env_file:
      - .env

networks:
  eseklugdorow:
    name: eseklugdorow
    external: true