services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8081
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - eseklugdorow
    env_file:
      - .env