services:
  credit_card:
    build: .credit_card/
    command: python manage.py runserver 0.0.0.0:8081
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    networks:
      - eseklugdorow
    env_file:
      - .env

networks:
  eseklugdorow:
    external: true